trained_model_parameter:
    setting:
        add_position_to_prediction: false
        add_vel_to_prediction: true
        add_yaw_to_prediction: true
        integrate_states: true
        integrate_vel: true
        integrate_yaw: true
    queue_size:
        acc_queue_size: 15
        steer_queue_size: 15
    lstm:
        update_lstm_len: 50
        predict_lstm_len: 50
    loss:
        integration_len: 15
        integration_weight: 1.0