/**:
  ros__parameters:
    stop_planner:
      stop_margin: 10.0 # stop margin distance from obstacle on the path [m]
      min_behavior_stop_margin: 10.0 # stop margin distance when any other stop point is inserted in stop margin [m]
      step_length: 0.5 # step length for pointcloud search range [m]
      extend_distance: 10.0 # extend trajectory to consider after goal obstacle in the extend_distance
      expand_stop_range: 0.0 # margin of vehicle footprint [m]
      expand_stop_range_l: 0.0 # margin of vehicle left footprint [m]
      expand_stop_range_r: 0.0 # margin of vehicle right footprint [m]
      mirror_width: 0.4 # mirror width [m]

    slow_down_planner:
      # slow down planner parameters
      forward_margin: 250.0   # margin distance from slow down point to vehicle front [m]
      backward_margin: 5.0 # margin distance from slow down point to vehicle rear [m]
      expand_slow_down_range: 1.9  # offset from vehicle side edge for expanding the search area of the surrounding point cloud [m]
      expand_slow_down_range_l: 0.4 # offset from vehicle left edge for expanding the search area of the surrounding point cloud [m]
      expand_slow_down_range_r: 1.9 # offset from vehicle right edge for expanding the search area of the surrounding point cloud [m]
      time_margin: 10  # if detect obstacle for more than time_margin, slow down start (integer)
      max_slow_down_vel: 4.16  #15km/h # max slow down velocity [m/s]
      min_slow_down_vel: 4.16  #15km/h # min slow down velocity [m/s]
      max_deceleration: 2.0 # for obstacle collision checker
      passing_param: 0.000023   #[-] set bigger, deceleration become bigger. for isuzu tyokusen suretigai.
      speed_thresh_high: 1.38 # [m/s]
      speed_thresh_low : 0.0 # [m/s]
      yaw_rate_thresh: 100.0 # [rad/s] <= need tuning parameter 100=disable
      curvature_stop: True # set "True", if curvature is high and searched vehicle, become stop mode. 
      curvature_thresh: 0.002 # [1/m]
      curvature_smoothing_num: 50 # [-]
      curve_forward_margin: 120.0  #150.0 # margin distance from slow down point to vehicle front in high curvature[m]
      curve_backward_margin: 5.0 # margin distance from slow down point to vehicle rear in high curvature[m]
      passing_param_for_curve: 0.00020   #[-] set bigger, deceleration become bigger. for isuzu tyokusen suretigai in high curvature.


      # slow down constraint parameters
      consider_constraints: False # set "True", if no decel plan found under jerk/dec constrains, relax target slow down vel
      forward_margin_min: 1.0 # min margin for relaxing slow down margin [m/s]
      forward_margin_span: -0.1 # fineness param for relaxing slow down margin [m/s]
      jerk_min_slow_down: -0.6 # min slow down jerk constraint [m/sss]
      jerk_span: -0.01 # fineness param for planning deceleration jerk [m/sss]
      jerk_start: -0.1 # init jerk used for deceleration planning [m/sss]
      slow_down_vel: 1.38 # target slow down velocity [m/s]

