/**:
  ros__parameters:
    detection_area:
      stop_margin: 0.0
      use_dead_line: false
      dead_line_margin: 5.0
      use_pass_judge_line: true
      state_clear_time: 2.0
      min_acc : -0.3  #for calc -0.5 < x

