name: sync-awf-latest

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  sync-awf-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Commit Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout awf-latest-tmp
          git remote add awf https://github.com/autowarefoundation/autoware.universe
          git fetch awf main
          git rebase awf/main

          git remote remove origin
          git remote add origin git@github.com:tier4/autoware.universe
          git push origin awf-latest-tmp --force
